# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 	desc "Push a new beta build to TestFlight"
  	lane :beta do
    		build_app(workspace: "SwiftRest.xcworkspace", scheme: "SwiftRest")
    		upload_to_testflight
  	end

	desc "Run Tests"
	lane :tests do
  		run_tests(scheme: "SwiftRestTests")
	end

	desc "clean xcode data"

	lane :clean_xcode do |options|
  		clear_derived_data()
  		sh("rm -rf ProjectName*zip")
  		sh("rm -rf ~/Library/Developer/Xcode/Archives/*")
	end
end
